# Generated by Django 4.0.2 on 2022-02-03 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_content_user_image_user_shortdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=uuid.uuid1, null=True, unique=True),
        ),
    ]
