# Generated by Django 4.0.2 on 2022-02-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
    ]
