# Generated by Django 4.0.2 on 2022-02-05 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=uuid.uuid1, null=True, unique=True),
        ),
    ]
