# Generated by Django 4.0.2 on 2022-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_rate_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shortdes',
        ),
    ]
