# Generated by Django 4.0.2 on 2022-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_content_remove_user_shortdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shortdes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
