# Generated by Django 4.0.1 on 2022-01-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0004_remove_books_writer'),
        ('blogs', '0002_blogs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_moudles.bookcategory'),
        ),
    ]
