# Generated by Django 4.0.1 on 2022-02-02 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=uuid.uuid1, null=True, unique=True),
        ),
    ]
