# Generated by Django 4.0.1 on 2022-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blogs_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(),
        ),
    ]
