# Generated by Django 4.0.2 on 2022-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_blogs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
