# Generated by Django 4.0.1 on 2022-01-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0003_bookwriter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='writer',
        ),
    ]
