# Generated by Django 4.0.1 on 2022-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0004_remove_books_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='books',
            name='short_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
