# Generated by Django 4.0.1 on 2022-01-31 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_moudles', '0006_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(related_name='bloglikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
