# Generated by Django 4.0.1 on 2022-01-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0007_books_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='likes',
        ),
    ]
