# Generated by Django 4.0.1 on 2022-01-31 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_moudles', '0008_remove_books_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='booksdislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='bookslikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='booksreaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='reading',
            field=models.ManyToManyField(blank=True, related_name='booksreading', to=settings.AUTH_USER_MODEL),
        ),
    ]
