# Generated by Django 4.0.1 on 2022-01-31 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_moudles', '0009_books_dislike_books_likes_books_readed_books_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookwriter',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookwriter',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='authordislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookwriter',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='bookwriter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='authorlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookwriter',
            name='short_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
