# Generated by Django 4.0.1 on 2022-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0010_bookwriter_content_bookwriter_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bookimages'),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
