# Generated by Django 4.0.1 on 2022-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0011_alter_books_image_alter_bookwriter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
