# Generated by Django 4.0.1 on 2022-01-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0013_books_testrel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='testrel',
        ),
        migrations.DeleteModel(
            name='tttest',
        ),
    ]
