# Generated by Django 4.0.1 on 2022-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0014_remove_books_testrel_delete_tttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, default='bookimages/product.jpg', null=True, upload_to='bookimages'),
        ),
    ]
