# Generated by Django 4.0.1 on 2022-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0015_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(default='bookimages/product.jpg', upload_to='bookimages'),
        ),
    ]
