# Generated by Django 4.0.1 on 2022-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0018_remove_books_category_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(upload_to='bookimages'),
        ),
    ]
