# Generated by Django 4.0.1 on 2022-02-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0023_bookcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True),
        ),
    ]
