# Generated by Django 4.0.1 on 2022-02-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0025_remove_bookcategory_slug_bookcategory_slugg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='slugg',
        ),
        migrations.AddField(
            model_name='bookwriter',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, unique=True),
        ),
    ]
