# Generated by Django 4.0.1 on 2022-02-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0028_remove_bookwriter_writerslug_bookcategory_titleslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='titleslug',
        ),
    ]
