# Generated by Django 4.0.1 on 2022-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0029_remove_bookcategory_titleslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True),
        ),
    ]
