# Generated by Django 4.0.1 on 2022-02-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0032_alter_books_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
