# Generated by Django 4.0.1 on 2022-02-02 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0033_remove_books_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=uuid.uuid1, null=True, unique=True),
        ),
    ]
