# Generated by Django 4.0.1 on 2022-02-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0035_bookcategory_slug_bookwriter_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookwriter',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='bookwriter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookwriter',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='bookwriter',
            name='short_description',
        ),
    ]
