# Generated by Django 4.0.2 on 2022-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0039_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='bookcat', to='main_moudles.bookcategory'),
        ),
    ]
