# Generated by Django 4.0.2 on 2022-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0040_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
