# Generated by Django 4.0.1 on 2022-02-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0035_bookcategory_slug_bookwriter_slug'),
        ('contact_us', '0003_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='forbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookcoments', to='main_moudles.books'),
        ),
    ]
