# Generated by Django 4.0.1 on 2022-02-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_moudles', '0039_alter_books_author'),
        ('contact_us', '0004_coments_forbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='forblog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogcoments', to='main_moudles.books'),
        ),
    ]
