# Generated by Django 4.0.1 on 2022-02-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_blogs_author'),
        ('contact_us', '0005_coments_forblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='forblog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogcoments', to='blogs.blogs'),
        ),
    ]
