# Generated by Django 4.0.1 on 2022-02-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0008_coments_itsuser_alter_coments_comentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='itsuser',
        ),
    ]
